# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  texture_test_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  texture_test_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  texture_test_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad texture_test

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/Glad -f Makefile config=$(Glad_config)
endif

texture_test: GLFW Glad
ifneq (,$(texture_test_config))
	@echo "==== Building texture_test ($(texture_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f texture_test.make config=$(texture_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C dependencies/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C dependencies/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C . -f texture_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   texture_test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"